baseURL = 'https://www.trdp.dev/blog/'
title = "Ryan Peel's Blog"
copyright = "Ryan Peel"
pagination.pagerSize = 10
languageCode = 'en-us'
theme = 'tailwind'
enableGitInfo = true

[markup]
  _merge = "deep"

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Posts"
    pageRef = "/posts"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"